spring.application.name=module62App


#spring.datasource.url=jdbc:h2:mem:testdb (H2 local mem)

#spring.datasource.url=jdbc:h2:file:./data/module62 (H2 file)
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username= sa
#spring.datasource.password=
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:mysql://localhost:3306/module62
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.datasource.username= root
spring.datasource.password= root
spring.jpa.hibernate.ddl-auto=update


